/**
 * Arabic-first digital-invitation demo library — data-driven renderer source.
 *
 * Source of truth: the approved 64-record seed matrix
 *   `03_Shared_Assets/wedding_invitation_demos/WEDDING_INVITATION_DEMO_SEED_64.json`
 * (8 occasion categories × 8 original style families; 32 static, 16 carousel,
 * 16 animated). This module transforms that matrix into typed records the
 * gallery + demo-detail renderers consume. One renderer, 64 records — never 64
 * copied components (site architecture §6).
 *
 * Hard rules carried into this data:
 *  - Every record is a DEMO. `demoLabelAr` always contains نموذج and is shown on
 *    every card. Nothing here is presented as a completed paid client project.
 *  - Visuals are original CSS/SVG/vector compositions generated by
 *    `InvitationPoster` from the style family + palette below. No stock photos,
 *    no competitor artwork, no relabelled work.
 *  - Demo names (راشد ومريم …) are original placeholder names, not real clients.
 *  - Demo-detail pages are `noindex,follow` at launch (`indexable: false`). SEO
 *    value comes from the service pages and the filterable gallery, not 64
 *    doorway pages (architecture §3).
 *
 * The Arabic color descriptors from the seed (`palette_ar`) are kept verbatim as
 * human-readable captions; the machine `palette` hex arrays are original to Big
 * Story and drive the SVG renderer.
 */

import type { Locale } from "@/lib/i18n";
import type { L } from "@/lib/i18n";

/* ------------------------------------------------------------------ *
 * Style families — 8 original palettes, one per seed style_en family. *
 * Each palette drives the vector poster: bg, ink (primary text on bg),*
 * accent (metal/leaf), soft (secondary fill). `light` = light ground  *
 * (dark ink) so the نموذج badge and text pick the right contrast.     *
 * ------------------------------------------------------------------ */

export type StyleKey =
  | "Majlis Pearl"
  | "Desert Moon"
  | "Emirati Geometry"
  | "Night Garden"
  | "Golden Palms"
  | "Emerald Arch"
  | "Burgundy Script"
  | "Pearl Sky";

export type StyleFamily = {
  key: StyleKey;
  nameAr: string;
  bg: string;
  bg2: string;
  ink: string;
  accent: string;
  soft: string;
  light: boolean;
};

export const styleFamilies: Record<StyleKey, StyleFamily> = {
  "Majlis Pearl": {
    key: "Majlis Pearl",
    nameAr: "لؤلؤة المجلس",
    bg: "#f5efe2",
    bg2: "#ece3d0",
    ink: "#5b4a2a",
    accent: "#c9a227",
    soft: "#e8dcc2",
    light: true,
  },
  "Desert Moon": {
    key: "Desert Moon",
    nameAr: "قمر الصحراء",
    bg: "#1b2340",
    bg2: "#2a3357",
    ink: "#efe6d2",
    accent: "#d8b978",
    soft: "#c9b592",
    light: false,
  },
  "Emirati Geometry": {
    key: "Emirati Geometry",
    nameAr: "هندسة إماراتية",
    bg: "#0d0d0f",
    bg2: "#17171a",
    ink: "#f6f6f1",
    accent: "#c9a227",
    soft: "#2a2a2e",
    light: false,
  },
  "Night Garden": {
    key: "Night Garden",
    nameAr: "حديقة الليل",
    bg: "#16213e",
    bg2: "#20305a",
    ink: "#f0e7ec",
    accent: "#cf9fb0",
    soft: "#8a93b0",
    light: false,
  },
  "Golden Palms": {
    key: "Golden Palms",
    nameAr: "نخيل ذهبي",
    bg: "#1f3d2f",
    bg2: "#2c5341",
    ink: "#f4efe0",
    accent: "#d3b25a",
    soft: "#7d9b7f",
    light: false,
  },
  "Emerald Arch": {
    key: "Emerald Arch",
    nameAr: "قوس الزمرد",
    bg: "#0f3d34",
    bg2: "#175046",
    ink: "#efe7d4",
    accent: "#c08a52",
    soft: "#6fa090",
    light: false,
  },
  "Burgundy Script": {
    key: "Burgundy Script",
    nameAr: "مخطوطة عنابية",
    bg: "#4a1522",
    bg2: "#651d2e",
    ink: "#f3e6d3",
    accent: "#e2c48f",
    soft: "#b07d84",
    light: false,
  },
  "Pearl Sky": {
    key: "Pearl Sky",
    nameAr: "سماء اللؤلؤ",
    bg: "#dde6ec",
    bg2: "#cbd8e2",
    ink: "#3f5265",
    accent: "#8aa0b3",
    soft: "#eef3f7",
    light: true,
  },
};

/* ------------------------------------------------------------------ *
 * Occasion categories — seed category_slug → owning service page.     *
 * ------------------------------------------------------------------ */

export type CategorySlug =
  | "wedding-invitation"
  | "katb-kitab"
  | "engagement-milka"
  | "save-the-date"
  | "wedding-announcement"
  | "newborn-announcement"
  | "graduation-invitation"
  | "birthday-invitation";

export type InvitationCategory = {
  slug: CategorySlug;
  nameAr: string;
  nameEn: string;
  /** Owning service page slug under /services */
  serviceSlug: string;
  /** Short Arabic occasion verb used in alt text, e.g. "زفاف" */
  occasionAr: string;
};

export const invitationCategories: InvitationCategory[] = [
  {
    slug: "wedding-invitation",
    nameAr: "دعوة زفاف إلكترونية",
    nameEn: "Digital wedding invitation",
    serviceSlug: "digital-wedding-invitations",
    occasionAr: "زفاف",
  },
  {
    slug: "katb-kitab",
    nameAr: "دعوة عقد قران",
    nameEn: "Katb Kitab / Aqd Qiran invitation",
    serviceSlug: "katb-kitab-invitations",
    occasionAr: "عقد قران",
  },
  {
    slug: "engagement-milka",
    nameAr: "دعوة خطوبة وملكة",
    nameEn: "Malka & engagement invitation",
    serviceSlug: "malka-engagement-invitations",
    occasionAr: "خطوبة وملكة",
  },
  {
    slug: "save-the-date",
    nameAr: "احفظوا التاريخ",
    nameEn: "Save the Date",
    serviceSlug: "wedding-save-the-date",
    occasionAr: "احفظوا التاريخ",
  },
  {
    slug: "wedding-announcement",
    nameAr: "إعلان زواج",
    nameEn: "Wedding announcement",
    serviceSlug: "wedding-announcements",
    occasionAr: "إعلان زواج",
  },
  {
    slug: "newborn-announcement",
    nameAr: "بشارة مولود",
    nameEn: "Newborn announcement",
    serviceSlug: "newborn-invitations-announcements",
    occasionAr: "بشارة مولود",
  },
  {
    slug: "graduation-invitation",
    nameAr: "دعوة تخرج",
    nameEn: "Graduation invitation",
    serviceSlug: "graduation-invitations",
    occasionAr: "تخرج",
  },
  {
    slug: "birthday-invitation",
    nameAr: "دعوة عيد ميلاد",
    nameEn: "Birthday invitation",
    serviceSlug: "birthday-invitations",
    occasionAr: "عيد ميلاد",
  },
];

const categoryBySlug: Record<string, InvitationCategory> = Object.fromEntries(
  invitationCategories.map((c) => [c.slug, c]),
);

/* ------------------------------------------------------------------ *
 * Format model.                                                       *
 * ------------------------------------------------------------------ */

export type DemoFormat = "static" | "carousel" | "animated";

export const formatLabels: Record<DemoFormat, L> = {
  static: { en: "Static card", ar: "بطاقة ثابتة" },
  carousel: { en: "Carousel", ar: "كاروسيل" },
  animated: { en: "Animated (motion)", ar: "متحرك" },
};

export const deliverableLabels: Record<DemoFormat, L> = {
  static: { en: "PNG / JPG", ar: "PNG / JPG" },
  carousel: { en: "PNG carousel", ar: "كاروسيل PNG" },
  animated: { en: "MP4", ar: "MP4" },
};

/* ------------------------------------------------------------------ *
 * Public record type (site architecture §6 required fields).         *
 * ------------------------------------------------------------------ */

export type InvitationDemo = {
  id: string;
  slug: string;
  categorySlug: CategorySlug;
  categoryNameAr: string;
  categoryNameEn: string;
  styleKey: StyleKey;
  styleAr: string;
  styleEn: string;
  paletteAr: string;
  palette: string[];
  format: DemoFormat;
  deliverable: string;
  demoNameAr: string;
  /** Original vector composition — resolved by InvitationPoster from styleKey. */
  asset: string;
  altAr: string;
  altEn: string;
  demoLabelAr: string;
  demoLabelEn: string;
  indexable: boolean;
  servicePath: string;
  relatedDemoIds: string[];
  uniqueDesignNotesAr: string;
  uniqueDesignNotesEn: string;
};

/* Raw seed rows (verbatim from WEDDING_INVITATION_DEMO_SEED_64.json). Kept as a
 * compact tuple table; the full typed records are derived once at module load so
 * palette/alt/related logic stays in one place. */
type SeedRow = [
  id: string,
  category: CategorySlug,
  slug: string,
  nameAr: string,
  styleEn: StyleKey,
  styleAr: string,
  paletteAr: string,
  format: DemoFormat,
];

// prettier-ignore
const seed: SeedRow[] = [
  ["DEMO-001","wedding-invitation","wedding-invitation-majlis-pearl-01","راشد ومريم","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-002","wedding-invitation","wedding-invitation-desert-moon-02","سلطان ونورة","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-003","wedding-invitation","wedding-invitation-emirati-geometry-03","حمد ولطيفة","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-004","wedding-invitation","wedding-invitation-night-garden-04","خالد وعائشة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-005","wedding-invitation","wedding-invitation-golden-palms-05","زايد ودانة","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-006","wedding-invitation","wedding-invitation-emerald-arch-06","ماجد وشيخة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-007","wedding-invitation","wedding-invitation-burgundy-script-07","سيف وغالية","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-008","wedding-invitation","wedding-invitation-pearl-sky-08","فارس وبسمة","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-009","katb-kitab","katb-kitab-majlis-pearl-01","راشد ومريم","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-010","katb-kitab","katb-kitab-desert-moon-02","سلطان ونورة","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-011","katb-kitab","katb-kitab-emirati-geometry-03","حمد ولطيفة","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-012","katb-kitab","katb-kitab-night-garden-04","خالد وعائشة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-013","katb-kitab","katb-kitab-golden-palms-05","زايد ودانة","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-014","katb-kitab","katb-kitab-emerald-arch-06","ماجد وشيخة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-015","katb-kitab","katb-kitab-burgundy-script-07","سيف وغالية","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-016","katb-kitab","katb-kitab-pearl-sky-08","فارس وبسمة","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-017","engagement-milka","engagement-milka-majlis-pearl-01","راشد ومريم","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-018","engagement-milka","engagement-milka-desert-moon-02","سلطان ونورة","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-019","engagement-milka","engagement-milka-emirati-geometry-03","حمد ولطيفة","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-020","engagement-milka","engagement-milka-night-garden-04","خالد وعائشة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-021","engagement-milka","engagement-milka-golden-palms-05","زايد ودانة","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-022","engagement-milka","engagement-milka-emerald-arch-06","ماجد وشيخة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-023","engagement-milka","engagement-milka-burgundy-script-07","سيف وغالية","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-024","engagement-milka","engagement-milka-pearl-sky-08","فارس وبسمة","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-025","save-the-date","save-the-date-majlis-pearl-01","راشد ومريم","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-026","save-the-date","save-the-date-desert-moon-02","سلطان ونورة","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-027","save-the-date","save-the-date-emirati-geometry-03","حمد ولطيفة","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-028","save-the-date","save-the-date-night-garden-04","خالد وعائشة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-029","save-the-date","save-the-date-golden-palms-05","زايد ودانة","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-030","save-the-date","save-the-date-emerald-arch-06","ماجد وشيخة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-031","save-the-date","save-the-date-burgundy-script-07","سيف وغالية","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-032","save-the-date","save-the-date-pearl-sky-08","فارس وبسمة","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-033","wedding-announcement","wedding-announcement-majlis-pearl-01","راشد ومريم","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-034","wedding-announcement","wedding-announcement-desert-moon-02","سلطان ونورة","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-035","wedding-announcement","wedding-announcement-emirati-geometry-03","حمد ولطيفة","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-036","wedding-announcement","wedding-announcement-night-garden-04","خالد وعائشة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-037","wedding-announcement","wedding-announcement-golden-palms-05","زايد ودانة","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-038","wedding-announcement","wedding-announcement-emerald-arch-06","ماجد وشيخة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-039","wedding-announcement","wedding-announcement-burgundy-script-07","سيف وغالية","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-040","wedding-announcement","wedding-announcement-pearl-sky-08","فارس وبسمة","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-041","newborn-announcement","newborn-announcement-majlis-pearl-01","نور","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-042","newborn-announcement","newborn-announcement-desert-moon-02","ليان","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-043","newborn-announcement","newborn-announcement-emirati-geometry-03","زايد","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-044","newborn-announcement","newborn-announcement-night-garden-04","ميرة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-045","newborn-announcement","newborn-announcement-golden-palms-05","سالم","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-046","newborn-announcement","newborn-announcement-emerald-arch-06","دانة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-047","newborn-announcement","newborn-announcement-burgundy-script-07","راشد","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-048","newborn-announcement","newborn-announcement-pearl-sky-08","هند","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-049","graduation-invitation","graduation-invitation-majlis-pearl-01","نور","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-050","graduation-invitation","graduation-invitation-desert-moon-02","ليان","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-051","graduation-invitation","graduation-invitation-emirati-geometry-03","زايد","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-052","graduation-invitation","graduation-invitation-night-garden-04","ميرة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-053","graduation-invitation","graduation-invitation-golden-palms-05","سالم","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-054","graduation-invitation","graduation-invitation-emerald-arch-06","دانة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-055","graduation-invitation","graduation-invitation-burgundy-script-07","راشد","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-056","graduation-invitation","graduation-invitation-pearl-sky-08","هند","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
  ["DEMO-057","birthday-invitation","birthday-invitation-majlis-pearl-01","نور","Majlis Pearl","لؤلؤة المجلس","عاجي، ذهبي، لؤلؤي","static"],
  ["DEMO-058","birthday-invitation","birthday-invitation-desert-moon-02","ليان","Desert Moon","قمر الصحراء","رملي، ليلي، ذهبي","carousel"],
  ["DEMO-059","birthday-invitation","birthday-invitation-emirati-geometry-03","زايد","Emirati Geometry","هندسة إماراتية","أبيض، أسود، ذهبي","animated"],
  ["DEMO-060","birthday-invitation","birthday-invitation-night-garden-04","ميرة","Night Garden","حديقة الليل","كحلي، وردي غباري، فضي","static"],
  ["DEMO-061","birthday-invitation","birthday-invitation-golden-palms-05","سالم","Golden Palms","نخيل ذهبي","أخضر نخيل، عاجي، ذهبي","static"],
  ["DEMO-062","birthday-invitation","birthday-invitation-emerald-arch-06","دانة","Emerald Arch","قوس الزمرد","زمردي، كريمي، نحاسي","carousel"],
  ["DEMO-063","birthday-invitation","birthday-invitation-burgundy-script-07","راشد","Burgundy Script","مخطوطة عنابية","عنابي، شامبانيا، عاجي","animated"],
  ["DEMO-064","birthday-invitation","birthday-invitation-pearl-sky-08","هند","Pearl Sky","سماء اللؤلؤ","أزرق ضبابي، أبيض، فضي","static"],
];

const DEMO_LABEL_AR = "نموذج تجريبي";
const DEMO_LABEL_EN = "Demo sample";

function paletteFor(style: StyleKey): string[] {
  const f = styleFamilies[style];
  return [f.bg, f.accent, f.soft, f.ink];
}

function altArFor(row: SeedRow): string {
  const [, category, , nameAr, , styleAr, paletteAr] = row;
  const cat = categoryBySlug[category];
  return `نموذج تجريبي — ${cat.nameAr} بأسماء ${nameAr}، بأسلوب ${styleAr} وألوان ${paletteAr}، تصميم أصلي من بيك ستوري.`;
}

function altEnFor(row: SeedRow): string {
  const [, category, , nameAr, styleEn] = row;
  const cat = categoryBySlug[category];
  return `Demo sample — ${cat.nameEn} in the ${styleEn} style for ${nameAr}. Original Big Story vector design.`;
}

function notesArFor(row: SeedRow): string {
  const [, category, , , , styleAr, paletteAr] = row;
  const cat = categoryBySlug[category];
  return `أسلوب ${styleAr}: لوحة ${paletteAr} مع تنسيق عربي من اليمين إلى اليسار. يُخصَّص لهذه المناسبة (${cat.nameAr}) بالأسماء والتاريخ والمكان والعبارة المفضّلة قبل التسليم.`;
}

function notesEnFor(row: SeedRow): string {
  const [, category, , , styleEn, , paletteAr] = row;
  const cat = categoryBySlug[category];
  return `${styleEn} style with a "${paletteAr}" palette and native right-to-left Arabic layout. Personalised for this occasion (${cat.nameEn}) with your names, date, venue and preferred wording before delivery.`;
}

/** Three related demos: same style family across other occasions (visual family
 *  browsing) — the seed's strongest cross-link axis. */
function relatedFor(row: SeedRow, all: SeedRow[]): string[] {
  const [id, category, , , styleEn] = row;
  const sameStyle = all.filter((r) => r[4] === styleEn && r[0] !== id);
  const otherOccasion = sameStyle.filter((r) => r[1] !== category);
  return (otherOccasion.length >= 3 ? otherOccasion : sameStyle).slice(0, 3).map((r) => r[0]);
}

export const invitationDemos: InvitationDemo[] = seed.map((row) => {
  const [id, category, slug, nameAr, styleEn, styleAr, paletteAr, format] = row;
  const cat = categoryBySlug[category];
  return {
    id,
    slug,
    categorySlug: category,
    categoryNameAr: cat.nameAr,
    categoryNameEn: cat.nameEn,
    styleKey: styleEn,
    styleAr,
    styleEn,
    paletteAr,
    palette: paletteFor(styleEn),
    format,
    deliverable: format === "static" ? "PNG/JPG" : format === "carousel" ? "PNG carousel" : "MP4",
    demoNameAr: nameAr,
    asset: `svg:${styleEn}`,
    altAr: altArFor(row),
    altEn: altEnFor(row),
    demoLabelAr: `${DEMO_LABEL_AR} — ${cat.nameAr} باسم ${nameAr}`,
    demoLabelEn: `${DEMO_LABEL_EN} — ${cat.nameEn}: ${nameAr}`,
    // Launch policy: gallery is the indexable surface; demo detail pages are
    // noindex,follow until each has a finished asset + unique 250+ word copy.
    indexable: false,
    servicePath: `/services/${cat.serviceSlug}`,
    relatedDemoIds: relatedFor(row, seed),
    uniqueDesignNotesAr: notesArFor(row),
    uniqueDesignNotesEn: notesEnFor(row),
  };
});

/* ------------------------------------------------------------------ *
 * Lookups.                                                            *
 * ------------------------------------------------------------------ */

export const invitationDemoSlugs = invitationDemos.map((d) => d.slug);

const demoBySlug = new Map(invitationDemos.map((d) => [d.slug, d]));
const demoById = new Map(invitationDemos.map((d) => [d.id, d]));

export function getDemo(slug: string): InvitationDemo | undefined {
  return demoBySlug.get(slug);
}

export function getDemoById(id: string): InvitationDemo | undefined {
  return demoById.get(id);
}

export function demosForCategory(categorySlug: CategorySlug): InvitationDemo[] {
  return invitationDemos.filter((d) => d.categorySlug === categorySlug);
}

/** Demos for the service page that owns a given service slug (or [] if none). */
export function demosForService(serviceSlug: string): InvitationDemo[] {
  const cat = invitationCategories.find((c) => c.serviceSlug === serviceSlug);
  return cat ? demosForCategory(cat.slug) : [];
}

export function getCategory(slug: CategorySlug): InvitationCategory | undefined {
  return categoryBySlug[slug];
}

/** Localised category label. */
export function categoryLabel(cat: InvitationCategory, locale: Locale): string {
  return locale === "ar" ? cat.nameAr : cat.nameEn;
}
